# -*- Makefile -*-
################################################################################
### Copyright 2007 VMware, Inc.  All rights reserved.
###
### This program is free software; you can redistribute it and/or modify
### it under the terms of version 2 of the GNU General Public License as
### published by the Free Software Foundation.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
################################################################################

dist_noinst_HEADERS += lib/open-vm-tools/include/backdoor_def.h
dist_noinst_HEADERS += lib/open-vm-tools/include/base64.h
dist_noinst_HEADERS += lib/open-vm-tools/include/bsd_output.h
dist_noinst_HEADERS += lib/open-vm-tools/include/bsdfmt.h
dist_noinst_HEADERS += lib/open-vm-tools/include/circList.h
dist_noinst_HEADERS += lib/open-vm-tools/include/codeset.h
dist_noinst_HEADERS += lib/open-vm-tools/include/compat/compat_stdarg.h
dist_noinst_HEADERS += lib/open-vm-tools/include/config.h
dist_noinst_HEADERS += lib/open-vm-tools/include/cpuid_info.h
dist_noinst_HEADERS += lib/open-vm-tools/include/cryptoError.h
dist_noinst_HEADERS += lib/open-vm-tools/include/dbllnklst.h
dist_noinst_HEADERS += lib/open-vm-tools/include/dictll.h
dist_noinst_HEADERS += lib/open-vm-tools/include/dynarray.h
dist_noinst_HEADERS += lib/open-vm-tools/include/dynbuf.h
dist_noinst_HEADERS += lib/open-vm-tools/include/err.h
dist_noinst_HEADERS += lib/open-vm-tools/include/escape.h
dist_noinst_HEADERS += lib/open-vm-tools/include/file.h
dist_noinst_HEADERS += lib/open-vm-tools/include/fileIO.h
dist_noinst_HEADERS += lib/open-vm-tools/include/fileLock.h
dist_noinst_HEADERS += lib/open-vm-tools/include/file_extensions.h
dist_noinst_HEADERS += lib/open-vm-tools/include/hashTable.h
dist_noinst_HEADERS += lib/open-vm-tools/include/hostType.h
dist_noinst_HEADERS += lib/open-vm-tools/include/hostinfo.h
dist_noinst_HEADERS += lib/open-vm-tools/include/includeCheck.h
dist_noinst_HEADERS += lib/open-vm-tools/include/iovector.h
dist_noinst_HEADERS += lib/open-vm-tools/include/localconfig.h
dist_noinst_HEADERS += lib/open-vm-tools/include/loglevel_defs.h
dist_noinst_HEADERS += lib/open-vm-tools/include/loglevel_user.h
dist_noinst_HEADERS += lib/open-vm-tools/include/msg.h
dist_noinst_HEADERS += lib/open-vm-tools/include/msgfmt.h
dist_noinst_HEADERS += lib/open-vm-tools/include/msgid.h
dist_noinst_HEADERS += lib/open-vm-tools/include/panic.h
dist_noinst_HEADERS += lib/open-vm-tools/include/posix.h
dist_noinst_HEADERS += lib/open-vm-tools/include/preference.h
dist_noinst_HEADERS += lib/open-vm-tools/include/productState.h
dist_noinst_HEADERS += lib/open-vm-tools/include/random.h
dist_noinst_HEADERS += lib/open-vm-tools/include/safetime.h
dist_noinst_HEADERS += lib/open-vm-tools/include/stats_file.h
dist_noinst_HEADERS += lib/open-vm-tools/include/stats_user_defs.h
dist_noinst_HEADERS += lib/open-vm-tools/include/stats_user_setup.h
dist_noinst_HEADERS += lib/open-vm-tools/include/str.h
dist_noinst_HEADERS += lib/open-vm-tools/include/strutil.h
dist_noinst_HEADERS += lib/open-vm-tools/include/su.h
dist_noinst_HEADERS += lib/open-vm-tools/include/syncMutex.h
dist_noinst_HEADERS += lib/open-vm-tools/include/syncWaitQ.h
dist_noinst_HEADERS += lib/open-vm-tools/include/timeutil.h
dist_noinst_HEADERS += lib/open-vm-tools/include/unicode.h
dist_noinst_HEADERS += lib/open-vm-tools/include/unicodeBase.h
dist_noinst_HEADERS += lib/open-vm-tools/include/unicodeOperations.h
dist_noinst_HEADERS += lib/open-vm-tools/include/unicodeTransforms.h
dist_noinst_HEADERS += lib/open-vm-tools/include/unicodeTypes.h
dist_noinst_HEADERS += lib/open-vm-tools/include/util.h
dist_noinst_HEADERS += lib/open-vm-tools/include/util_shared.h
dist_noinst_HEADERS += lib/open-vm-tools/include/uuid.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_assert.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_atomic.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_basic_asm.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_basic_asm_x86.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_basic_defs.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_basic_types.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_ctype.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_product.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_tools_version.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vm_version.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vmstdio.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vmware.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vmware_pack_begin.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vmware_pack_end.h
dist_noinst_HEADERS += lib/open-vm-tools/include/vmware_pack_init.h
dist_noinst_HEADERS += lib/open-vm-tools/include/x86cpuid.h
