# -*- Makefile -*-
################################################################################
# Copyright 2008 VMware, Inc.  All rights reserved.
#
# This file is part of VMware View Open Client.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation version 2.1 and no later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the Lesser GNU General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA.
################################################################################

dist_noinst_HEADERS += lib/bora/include/asyncsocket.h
dist_noinst_HEADERS += lib/bora/include/basicHttp.h
dist_noinst_HEADERS += lib/bora/include/crypto.h
dist_noinst_HEADERS += lib/bora/include/cryptoBuffer.h
dist_noinst_HEADERS += lib/bora/include/cryptoCipher.h
dist_noinst_HEADERS += lib/bora/include/cryptoDict.h
dist_noinst_HEADERS += lib/bora/include/cryptoFips.h
dist_noinst_HEADERS += lib/bora/include/cryptoHash.h
dist_noinst_HEADERS += lib/bora/include/cryptoPassword.h
dist_noinst_HEADERS += lib/bora/include/cryptoRandom.h
dist_noinst_HEADERS += lib/bora/include/cryptoSector.h
dist_noinst_HEADERS += lib/bora/include/dictionary.h
dist_noinst_HEADERS += lib/bora/include/keyLocator.h
dist_noinst_HEADERS += lib/bora/include/keySafe.h
dist_noinst_HEADERS += lib/bora/include/log.h
dist_noinst_HEADERS += lib/bora/include/logInt.h
dist_noinst_HEADERS += lib/bora/include/loglevel_tools.h
dist_noinst_HEADERS += lib/bora/include/mallocLinux.h
dist_noinst_HEADERS += lib/bora/include/mallocTracker.h
dist_noinst_HEADERS += lib/bora/include/poll.h
dist_noinst_HEADERS += lib/bora/include/pollImpl.h
dist_noinst_HEADERS += lib/bora/include/sig.h
dist_noinst_HEADERS += lib/bora/include/sigPosix.h
dist_noinst_HEADERS += lib/bora/include/ssl.h
dist_noinst_HEADERS += lib/bora/include/sslFunctionList.h
dist_noinst_HEADERS += lib/bora/include/sslPRNG.h
dist_noinst_HEADERS += lib/bora/include/sslWrapper.h
dist_noinst_HEADERS += lib/bora/include/syncRecMutex.h
dist_noinst_HEADERS += lib/bora/include/url.h
dist_noinst_HEADERS += lib/bora/include/urlAppend.h
dist_noinst_HEADERS += lib/bora/include/urlTable.h
dist_noinst_HEADERS += lib/bora/include/vcpuid.h
dist_noinst_HEADERS += lib/bora/include/vmlocale.h
dist_noinst_HEADERS += lib/bora/include/vthread.h
dist_noinst_HEADERS += lib/bora/include/vthreadBase.h
