.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH vmware-view-tunnel 1 "OCTOBER 2008" Linux "User Commands"
.SH NAME
vmware-view-tunnel \- VMware View Open Client
.SH SYNOPSIS
.B vmware-view-tunnel
.I [options]
.SH DESCRIPTION
.B vmware-view-tunnel
creates a tunneled connection to the View Connection Server.
.SH DOCUMENTATION
See View_Client_Help.pdf for full documentation.
