.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH vmware-view 1 "OCTOBER 2008" Linux "User Commands"
.SH NAME
vmware-view \- VMware View Open Client
.SH SYNOPSIS
.B vmware-view
.I [options]
.SH DESCRIPTION
.B vmware-view
allows users to connect to desktops on a View Connection
Server.
.SH DOCUMENTATION
See View_Client_Help.pdf for full documentation.
